name: Artemis Night
url: https://github.com/yuugou727/hexo-theme-artemis-night

menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  # GitHub: 
  RSS: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
